# Generated by Django 2.0.4 on 2018-04-15 11:25

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_text', models.TextField(verbose_name='공통 텍스트')),
                ('naver_text', models.TextField(verbose_name='네이버카페 텍스트')),
                ('instagram_text', models.TextField(verbose_name='인스타그램 텍스트')),
                ('facebook_text', models.TextField(verbose_name='페이스북 텍스트')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to=app.models.gallery_upload_path, verbose_name='사진')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='노출순서')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.FileField(upload_to=app.models.profile_upload_path, verbose_name='프로필사진')),
                ('name', models.CharField(max_length=32, verbose_name='이름')),
                ('introduce', models.TextField(verbose_name='소개')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='노출순서')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='수업명')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, '월'), (2, '화'), (3, '수'), (4, '목'), (5, '금'), (6, '토'), (7, '일')], verbose_name='요일')),
                ('class_room', models.PositiveSmallIntegerField(choices=[(1, '강의실1'), (2, '강의실2'), (3, '강의실3')], verbose_name='강의실')),
                ('start_time', models.FloatField(help_text='11부터 21까지. 오후 3시 30분이면, 15.5', verbose_name='시작시간')),
                ('end_time', models.FloatField(help_text='11부터 21까지. 예) 오후 3시 30분 => 15.5', verbose_name='종료시간')),
                ('color', models.CharField(help_text='#을 포함한 색상 코드. 예) 빨간색 => #ff0000', max_length=9, verbose_name='컬러코드')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'ordering': ['day_of_week', 'class_room'],
            },
        ),
    ]
