# Generated by Django 2.0.4 on 2018-04-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_text', models.TextField(verbose_name='커뮤니티 텍스트')),
                ('naver_text', models.TextField(verbose_name='네이버카페 텍스트')),
                ('instagram_text', models.TextField(verbose_name='인스타그램 텍스트')),
                ('facebook_text', models.TextField(verbose_name='페이스북 텍스트')),
                ('timetable_text', models.TextField(verbose_name='수업시간표 텍스트')),
            ],
        ),
        migrations.DeleteModel(
            name='Community',
        ),
    ]
