# Generated by Django 2.1 on 2018-08-23 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180416_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='수업명')),
                ('introduce', models.TextField(verbose_name='소개')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='name',
        ),
        migrations.AddField(
            model_name='timetable',
            name='classinfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.ClassInfo', verbose_name='수업'),
            preserve_default=False,
        ),
    ]
