# Generated by Django 2.1 on 2018-09-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180831_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoninfo',
            name='community_text',
        ),
        migrations.RemoveField(
            model_name='commoninfo',
            name='facebook_text',
        ),
        migrations.RemoveField(
            model_name='commoninfo',
            name='instagram_text',
        ),
        migrations.RemoveField(
            model_name='commoninfo',
            name='naver_text',
        ),
        migrations.AddField(
            model_name='commoninfo',
            name='about_link_m',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='학원소개더보기 링크(모바일)'),
        ),
        migrations.AddField(
            model_name='commoninfo',
            name='about_link_pc',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='학원소개더보기 링크(PC)'),
        ),
        migrations.AddField(
            model_name='commoninfo',
            name='about_text',
            field=models.TextField(blank=True, null=True, verbose_name='ABOUT 텍스트'),
        ),
        migrations.AddField(
            model_name='commoninfo',
            name='class_link_1',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='전공반 안내링크'),
        ),
        migrations.AddField(
            model_name='commoninfo',
            name='class_link_2',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='어린이취미반 안내링크'),
        ),
        migrations.AddField(
            model_name='commoninfo',
            name='class_link_3',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='성인취미반 안내링크'),
        ),
        migrations.AddField(
            model_name='commoninfo',
            name='contact_text',
            field=models.TextField(blank=True, null=True, verbose_name='CONTACT 텍스트'),
        ),
        migrations.AddField(
            model_name='commoninfo',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='페이스북 링크'),
        ),
        migrations.AddField(
            model_name='commoninfo',
            name='footer_text',
            field=models.TextField(blank=True, null=True, verbose_name='FOOTER 텍스트'),
        ),
        migrations.AddField(
            model_name='commoninfo',
            name='foreigner_text',
            field=models.TextField(blank=True, null=True, verbose_name='FOREIGNER 텍스트'),
        ),
        migrations.AddField(
            model_name='commoninfo',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='인스타그램 링크'),
        ),
        migrations.AddField(
            model_name='commoninfo',
            name='location_text',
            field=models.TextField(blank=True, null=True, verbose_name='LOCATION 텍스트'),
        ),
        migrations.AddField(
            model_name='commoninfo',
            name='navercafe_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='네이버카페 링크'),
        ),
        migrations.AddField(
            model_name='commoninfo',
            name='sungnamvallet_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='성남시티발레단 링크'),
        ),
        migrations.AddField(
            model_name='commoninfo',
            name='teachers_link_m',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='강사소개더보기 링크(모바일)'),
        ),
        migrations.AddField(
            model_name='commoninfo',
            name='teachers_link_pc',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='강사소개더보기 링크(PC)'),
        ),
        migrations.AddField(
            model_name='commoninfo',
            name='vdenie_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='브이데니에 링크'),
        ),
        migrations.AlterField(
            model_name='commoninfo',
            name='timetable_text',
            field=models.TextField(blank=True, null=True, verbose_name='수업시간표 텍스트'),
        ),
    ]
