# Generated by Django 2.1 on 2018-09-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180924_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoninfo',
            name='cs_link_m',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='온라인상담실 링크(모바일)'),
        ),
        migrations.AddField(
            model_name='commoninfo',
            name='cs_link_pc',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='온라인상담실 링크(PC)'),
        ),
        migrations.AddField(
            model_name='commoninfo',
            name='notice_link_m',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='공지사항 링크(모바일)'),
        ),
        migrations.AddField(
            model_name='commoninfo',
            name='notice_link_pc',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='공지사항 링크(PC)'),
        ),
    ]
