# Generated by Django 2.1 on 2019-10-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180925_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoninfo',
            name='intro_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='첫화면배경이미지'),
        ),
    ]
