# Generated by Django 2.1 on 2019-10-27 14:42

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_commoninfo_intro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoninfo',
            name='intro_image',
            field=models.FileField(blank=True, null=True, upload_to=app.models.intro_upload_path, verbose_name='첫화면배경이미지'),
        ),
    ]
