# Generated by Django 2.1 on 2019-11-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191027_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='display_order_m',
            field=models.PositiveIntegerField(default=0, verbose_name='노출순서(모바일)'),
        ),
    ]
