# Generated by Django 2.1 on 2019-11-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_gallery_display_order_m'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={},
        ),
    ]
